[advisories]
# advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
ignore = [
    # CVE-2025-67897 in Sequoia, we don't decrypt packets from attackers (just journalists)
    "RUSTSEC-2025-0136"
]

# Output Configuration
[output]
deny = ["warnings"]
quiet = false

# Target Configuration
[target]
arch = "x86_64" # Ignore advisories for CPU architectures other than this one
os = "linux" # Ignore advisories for operating systems other than this one
