name: Package builds
on:
  merge_group:
  push:
    branches: ["develop", "release/**"]
  pull_request:
    types: ["opened", "synchronize"]

# Only build for latest push/PR unless it's main or release/
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith( github.ref, 'refs/heads/release/' ) }}

defaults:
  run:
    shell: bash

jobs:
  build-debs:
    strategy:
      matrix:
        build: [one, two]
        versions:
          - ubuntu: noble
            python: "3.12"
    # TODO: change this back to ubuntu-latest once it is consistently 24.04
    runs-on: ubuntu-24.04
    outputs:
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.versions.python }}
      - name: Build SecureDrop packages
        run: |
          OS_VERSION=${{ matrix.versions.ubuntu }} ./builder/build-debs.sh
      - name: Build OSSEC packages
        run: |
          OS_VERSION=${{ matrix.versions.ubuntu }} WHAT=ossec ./builder/build-debs.sh
      - name: Build admin packages
        run: |
          OS_VERSION=${{ matrix.versions.ubuntu }} WHAT=admin ./builder/build-debs.sh
      - uses: actions/upload-artifact@v6
        id: upload
        with:
          name: ${{ matrix.versions.ubuntu }}-${{ matrix.build }}
          path: build/${{ matrix.versions.ubuntu }}
          if-no-files-found: error

  reproducible-debs:
    strategy:
      matrix:
        ubuntu_version: [noble]
    runs-on: ubuntu-latest
    container: debian:bookworm
    needs:
      - build-debs
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes diffoscope-minimal xz-utils \
            --no-install-recommends
      - uses: actions/download-artifact@v7
        with:
          pattern: "${{ matrix.ubuntu_version }}-*"
      - name: diffoscope
        run: |
          find . -name '*.deb' -exec sha256sum {} \;
          # FIXME: securedrop-app-code isn't reproducible
          for pkg in ossec-agent ossec-server securedrop-config securedrop-keyring securedrop-ossec-agent securedrop-ossec-server securedrop-admin
          do
              echo "Checking ${pkg}..."
              diffoscope ${{ matrix.ubuntu_version }}-one/${pkg}_*.deb ${{ matrix.ubuntu_version }}-two/${pkg}_*.deb
          done
